POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Learn Spring Boot",
  "description": "Complete CRUD APIs"
}

###
PUT http://localhost:8080/api/tasks/1
Content-Type: application/json

{
  "title": "Master Spring Boot",
  "description": "Complete CRUD + JWT",
  "status": "IN_PROGRESS"
}
###
GET http://localhost:8080/api/tasks

###
GET http://localhost:8080/api/tasks/1

###
GET http://localhost:8080/api/tasks?status=TODO
###
GET http://localhost:8080/api/tasks

###
GET http://localhost:8080/api/tasks?status=TODO

###
DELETE http://localhost:8080/api/tasks/1
###
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title":"Learn JWT",
  "description":"Implement authentication",
  "status":"TODO"
}
###
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title":"",
  "description":""
}
###
GET http://localhost:8080/api/tasks/999
###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Tanmay",
  "email": "tanmay@gmail.com",
  "password": "123456"
}