POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title": "Learn Spring Boot",
  "description": "Complete CRUD APIs"
}

###
PUT http://localhost:8080/api/tasks/1
Content-Type: application/json

{
  "title": "Master Spring Boot",
  "description": "Complete CRUD + JWT",
  "status": "IN_PROGRESS"
}
###
GET http://localhost:8080/api/tasks

###
GET http://localhost:8080/api/tasks/1

###
GET http://localhost:8080/api/tasks?status=TODO
###
GET http://localhost:8080/api/tasks

###
GET http://localhost:8080/api/tasks?status=TODO

###
DELETE http://localhost:8080/api/tasks/1
###
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title":"Learn JWT",
  "description":"Implement authentication",
  "status":"TODO"
}
###
POST http://localhost:8080/api/tasks
Content-Type: application/json

{
  "title":"",
  "description":""
}
###
GET http://localhost:8080/api/tasks/999
###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Tanmay",
  "email": "tanmay@gmail.com",
  "password": "123456"
}


### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Tanmay",
  "email": "tanmay2@gmail.com",
  "password": "123456"
}

###

### Login User
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tanmay2@gmail.com",
  "password": "123456"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tanmay2@gmail.com",
  "password": "123456"
}

> {% client.global.set("token", response.body.token); %}

###
### Without Token
GET http://localhost:8080/api/tasks

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tanmay2@gmail.com",
  "password": "123456"
}

> {% client.global.set("token", response.body.token); %}

###

### With Token
GET http://localhost:8080/api/tasks
Authorization: Bearer {{token}}

### Get Tasks
GET http://localhost:8080/api/tasks
Authorization: Bearer {{token}}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tanmay2@gmail.com",
  "password": "123456"
}

> {% client.global.set("token", response.body.token); %}

###

### Create Task
POST http://localhost:8080/api/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Spring Security",
  "description": "Complete user specific task feature",
  "status": "TODO"
}

###

### Get My Tasks
GET http://localhost:8080/api/tasks
Authorization: Bearer {{token}}
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tanmay2@gmail.com",
  "password": "123456"
}


###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Tanmay",
  "email": "tanmay1205@gmail.com",
  "password": "Password@123"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tanmay1205@gmail.com",
  "password": "Password@123"
}

###
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "3a94123b-4772-4144-b00e-f0184dc09231"
}

###
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "3a94123b-4772-4144-b00e-f0184dc09231"
}


###
POST http://localhost:8080/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YW5tYXkxMjA1QGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzg1NDM3OTg3LCJleHAiOjE3ODU1MjQzODd9.WFfdi8UQjC-9-TIiLLqlEs1kHe-nX8RNWX38Wcqdpzg
Content-Type: application/json

{
  "currentPassword":"Password@123",
  "newPassword":"Password@456"
}


###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tanmay1205@gmail.com",
  "password": "Password@456"
}

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "Tanmay Sarode",
  "email": "tanmaysarode512@gmail.com",
  "password": "Password@123"
}

###
POST http://localhost:8080/api/auth/forgot-password
Content-Type: application/json

{
  "email": "tanmaysarode512@gmail.com"
}

###
POST http://localhost:8080/api/auth/reset-password
Content-Type: application/json

{
  "token": "29c6a207-ca01-46e5-9a5a-5a40e8e58c95",
  "newPassword": "Password@789"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email":"tanmaysarode512@gmail.com",
  "password":"Password@789"
}

###
GET http://localhost:8080/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YW5tYXlzYXJvZGU1MTJAZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODU0NDExMDcsImV4cCI6MTc4NTUyNzUwN30.X8CS4kvvB3ryw6nIpLNd1W2dL5K4KfZLCgT32HhP1Cw

###
PUT http://localhost:8080/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YW5tYXlzYXJvZGU1MTJAZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODU0NDExMDcsImV4cCI6MTc4NTUyNzUwN30.X8CS4kvvB3ryw6nIpLNd1W2dL5K4KfZLCgT32HhP1Cw
Content-Type: application/json

{
  "name": "Tanmay S. Sarode",
  "email": "tanmaysarode512@gmail.com"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email":"tanmay@gmail.com",
  "password":"123456"
}

###
DELETE http://localhost:8080/api/users/account
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YW5tYXlAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzg1NDQxMzY1LCJleHAiOjE3ODU1Mjc3NjV9.XsIX-LXlDnHGZ8kspPoZS7E2uzEFSLRfCMBaF5vb5Yg


### Upload Profile Image
POST http://localhost:8080/api/users/profile/image
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YW5tYXlzYXJvZGU1MTJAZ21haWwuY29tIiwicm9sZSI6IlVTRVIiLCJpYXQiOjE3ODU0NDI4OTIsImV4cCI6MTc4NTUyOTI5Mn0.3MQcOoKmSjTtFq7bTKh_UgFgQksCVSRofGTGXxw-CLY
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="profile.jpeg"
Content-Type: image/jpeg

< C:\Users\TANMAY\Downloads\profile.jpeg
--WebAppBoundary--